global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'reops-event-proxy'
    metrics_path: '/internal/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8084']
  - job_name: 'reops-umami-consumer'
    metrics_path: '/internal/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8082']