spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    topic: reops-insight-event
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: ""
      ssl.truststore.type: JKS
      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH}
      ssl.truststore.password: ${KAFKA_CREDSTORE_PASSWORD}
      ssl.keystore.type: PKCS12
      ssl.keystore.location: ${KAFKA_KEYSTORE_PATH}
      ssl.keystore.password: ${KAFKA_CREDSTORE_PASSWORD}
      ssl.key.password: ${KAFKA_CREDSTORE_PASSWORD}
      reconnect.backoff.ms: 5000
      reconnect.backoff.max.ms: 1000
      auto.offset.reset: earliest
